=== illdikko/XML/Exercice2/Exercice2.dtd
<!ELEMENT annuaire (personne*)>
<!ELEMENT personne (nom,prenom,adresse,telephones,emails)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT adresse (rue,numero?,boite?,codePostal,ville,pays)>
<!ELEMENT rue (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT boite (#PCDATA)>
<!ELEMENT codePostal (#PCDATA)>
<!ELEMENT ville (#PCDATA)>
<!ELEMENT pays (#PCDATA)>
<!ELEMENT telephones (telephone*)>
<!ELEMENT telephone (typeNumero,numero)>
<!ELEMENT typeNumero (#PCDATA)>
<!ELEMENT emails (email)>
<!ELEMENT email (typeEmail,adresseEmail)>
<!ELEMENT typeEmail (#PCDATA)>
<!ELEMENT adresseEmail (#PCDATA)>

=== illdikko/XML/Exercice2/Exercice2.xml
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<!DOCTYPE annuaire SYSTEM "Exercice2.dtd">



<annuaire>
    <personne>
        <nom>Orianne</nom>
        <prenom>Maya</prenom>
        <adresse>
            <rue>Rue d'Orianne</rue>
            <numero>1</numero>
            <boite>32</boite>
            <codePostal>1000</codePostal>
            <ville>Bruxelles</ville>
            <pays>Belgique</pays>
        </adresse>
        <telephones>
            <telephone>
                <typeNumero></typeNumero>
                <numero></numero>
            </telephone>
        </telephones>
        <emails>
            <email>
                <typeEmail>Perso</typeEmail>
                <adresseEmail>mayaorianne@gmail.com</adresseEmail>
            </email>
        </emails>
    </personne>
    <personne>
        <nom>Drzazgowska</nom>
        <prenom>Katarzyna</prenom>
        <adresse>
            <rue>Rue de Pologne</rue>
            <numero>32</numero>
            <boite>2</boite>
            <codePostal>1020</codePostal>
            <ville>Ixelles</ville>
            <pays>Belgique</pays>
        </adresse>
        <telephones>
            <telephone>
                <typeNumero></typeNumero>
                <numero></numero>
            </telephone>
        </telephones>
        <emails>
            <email>
                <typeEmail>Perso</typeEmail>
                <adresseEmail>mayaorianne@gmail.com</adresseEmail>
            </email>
        </emails>
    </personne>
</annuaire>
